# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev.js CI

on: 
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

    
jobs:
  build:
    runs-on: stage.docs.plus
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Etherpad plugins
      run: >
        npm install --no-save --legacy-peer-deps
        ep_adminpads2
        https://github.com/samirsayyad/ep_bottom_chat_bar
        https://github.com/ether/ep_comments_page
        https://github.com/ether/ep_cursortrace
        https://github.com/samirsayyad/ep_custom_header_message
        https://github.com/samirsayyad/ep_docs_plus_customize#c68bc28
        https://github.com/samirsayyad/ep_full_hyperlinks#48e24d1
        https://github.com/samirsayyad/ep_headings2#f88ac17
        ep_hide_line_numbers
        https://github.com/samirsayyad/ep_insert_media#35b26c5
        https://github.com/samirsayyad/ep_loading_pad#84a888f
        ep_monetization
        https://github.com/samirsayyad/ep_profile_modal#d8d4112
        ep_remove_embed
        https://github.com/samirsayyad/ep_set_title_on_pad#b1688b0
        https://github.com/samirsayyad/ep_table_of_contents#326ccfc
        https://github.com/HMarzban/ep_wrtc_heading#56ab52e
        # https://github.com/ether/ep_sticky_attributes.git

    - name: Install all dependencies and symlink for ep_etherpad-lite
      run: src/bin/installDeps.sh
      
    - name: Run pm2 docsplus instance
      run: DB_NAME=${GITHUB_REF#refs/heads/} pm2 start temp/ecosystem.config.js --only  ${GITHUB_REF#refs/heads/}

    - name: Run pm2 ws.router instance
      run: DB_NAME=${GITHUB_REF#refs/heads/} pm2 reload temp/pm2.start.config.js --only ws_${GITHUB_REF#refs/heads/}

    env:
      DB_USER : ${{secrets.PG_USER}}
      DB_PASS : ${{secrets.PG_PASS}}
      DB_HOST : ${{secrets.PG_HOST}}
      DB_TYPE : postgres
      DB_PORT : ${{secrets.PG_PORT}}
      MEDIA_BUCKET_NAME : ${{secrets.MEDIA_BUCKET_NAME}}
      BUCKET_S3_SERVER : ${{secrets.BUCKET_S3_SERVER}}
      ACCESS_KEY_SECRET : ${{secrets.ACCESS_KEY_SECRET}}
      ACCESS_KEY_ID : ${{secrets.ACCESS_KEY_ID}}
