# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update.js CI

on:
  push:
    branches: [ update ]
  pull_request:
    branches: [ update ]

jobs:
  build:

    runs-on: update.docs.plus

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Etherpad plugins
      run: >
        npm install --no-save --legacy-peer-deps
        https://github.com/samirsayyad/ep_bottom_chat_bar
        https://github.com/ether/ep_comments_page
        https://github.com/ether/ep_cursortrace
        https://github.com/samirsayyad/ep_custom_header_message
        https://github.com/samirsayyad/ep_full_hyperlinks#ce4133c
        https://github.com/samirsayyad/ep_headings2#f88ac17
        ep_hide_line_numbers
        https://github.com/samirsayyad/ep_insert_media#35b26c5
        ep_monetization
        https://github.com/samirsayyad/ep_profile_modal#513e955
        ep_remove_embed
        https://github.com/samirsayyad/ep_set_title_on_pad#b1688b0
        https://github.com/ether/ep_sticky_attributes
        https://github.com/samirsayyad/ep_table_of_contents#326ccfc
        # https://github.com/samirsayyad/ep_loading_pad#84a888f
        # https://github.com/samirsayyad/ep_docs_plus_customize#fd5eab7
        # https://github.com/HMarzban/ep_wrtc_heading#3b42f23

    - name: Install all dependencies and symlink for ep_etherpad-lite
      run: src/bin/installDeps.sh


    # - run: npm run build --if-present
    - run: DB_NAME=${GITHUB_REF#refs/heads/} pm2 start ecosystem.config.js --only  ${GITHUB_REF#refs/heads/}
    env:
      DB_USER : ${{secrets.PG_USER}}
      DB_PASS : ${{secrets.PG_PASS}}
      DB_HOST : ${{secrets.PG_HOST}}
      MEDIA_BUCKET_NAME : ${{secrets.MEDIA_BUCKET_NAME}}
      BUCKET_S3_SERVER : ${{secrets.BUCKET_S3_SERVER}}
      ACCESS_KEY_SECRET : ${{secrets.ACCESS_KEY_SECRET}}
      ACCESS_KEY_ID : ${{secrets.ACCESS_KEY_ID}}
      DB_TYPE : postgres
      DB_PORT : ${{secrets.PG_PORT}}
      PORT : 9005,
